"""HTML report generation — ported from the original dashboard.py
(generate_html_report), restyled as a Jinja-free f-string template.
"""
from datetime import datetime

COLOR_MAP = {
    "Early Payment": "#9B7CB6",
    "In-House Factoring": "#F0A868",
    "Bank Financing": "#E07A7A",
}


def render_report(rec: dict) -> str:
    method = rec["recommended_method"]
    c = COLOR_MAP[method]
    ts = datetime.now().strftime("%B %d, %Y at %H:%M")
    sel = {m: ("✅" if m == method else "") for m in COLOR_MAP}
    rp, pc = rec["retail_price"], rec["production_cost"]
    margin = (rp - pc) / rp * 100

    return f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"><style>
body{{font-family:'Inter','Segoe UI',system-ui,sans-serif;max-width:800px;
margin:40px auto;color:#333;line-height:1.6;background:#f4f5f7}}
.header{{background:#3B2F4D;color:#fff;padding:32px;border-radius:6px;
margin-bottom:30px;box-shadow:0 4px 12px rgba(59,47,77,.15)}}
.header h1{{margin:0 0 8px;font-size:24px;font-weight:600;letter-spacing:-.5px}}
.header p{{margin:0;opacity:.85;font-size:14px}}
.section{{background:#fff;border-radius:6px;padding:24px;margin-bottom:24px;
box-shadow:0 2px 8px rgba(0,0,0,.04)}}
.section h2{{color:#3B2F4D;margin-top:0;font-size:16px;font-weight:600;
border-bottom:2px solid #6A4C8C;padding-bottom:10px;margin-bottom:16px}}
.metrics-grid{{display:grid;grid-template-columns:1fr 1fr;gap:16px}}
.metric-box{{background:#f8f9fa;border:1px solid #e9ecef;border-radius:4px;padding:14px}}
.metric-label{{font-size:12px;color:#6c757d;margin-bottom:6px;font-weight:500}}
.metric-value{{font-size:18px;font-weight:700;color:#3B2F4D}}
.recommendation-box{{background:{c};color:#fff;border-radius:6px;padding:20px;
margin-bottom:16px;box-shadow:0 4px 10px rgba(0,0,0,.08)}}
.recommendation-box h2{{margin:0 0 8px;font-size:22px;font-weight:600}}
.recommendation-box p{{margin:0;opacity:.9;font-size:14px}}
.justification{{background:#fff;border-left:4px solid {c};padding:16px;
border-radius:0 4px 4px 0;font-size:14px;color:#444}}
.footer{{text-align:center;font-size:12px;color:#999;margin-top:30px;
padding-top:20px;border-top:1px solid #dee2e6}}
table{{width:100%;border-collapse:collapse;margin-top:12px}}
th{{background:#5C456E;color:#fff;padding:12px;text-align:left;font-size:13px;font-weight:600}}
td{{padding:12px;border-bottom:1px solid #e9ecef;font-size:13px}}
tr:nth-child(even) td{{background:#f8f9fa}}
</style></head><body>
<div class="header">
  <h1>Supply Chain Finance Recommendation Report</h1>
  <p>Generated: {ts} &nbsp;|&nbsp; Based on Chen, Lu &amp; Cai (2020)</p>
</div>
<div class="section"><h2>Supplier Parameters</h2><div class="metrics-grid">
  <div class="metric-box"><div class="metric-label">Retail Price</div>
    <div class="metric-value">${rp:.2f}/unit</div></div>
  <div class="metric-box"><div class="metric-label">Production Cost</div>
    <div class="metric-value">${pc:.2f}/unit</div></div>
  <div class="metric-box"><div class="metric-label">Cost Ratio</div>
    <div class="metric-value">{rec['cost_ratio']:.2f}</div></div>
  <div class="metric-box"><div class="metric-label">Profit Margin</div>
    <div class="metric-value">{margin:.1f}%</div></div>
</div></div>
<div class="section"><h2>Demand Risk Analysis</h2><div class="metrics-grid">
  <div class="metric-box"><div class="metric-label">Mean Demand</div>
    <div class="metric-value">{rec['mean_demand']:.0f} units</div></div>
  <div class="metric-box"><div class="metric-label">Demand Volatility (CV)</div>
    <div class="metric-value">{rec['demand_cv']*100:.1f}%</div></div>
  <div class="metric-box"><div class="metric-label">Risk Level</div>
    <div class="metric-value">{rec['risk_level']}</div></div>
  <div class="metric-box"><div class="metric-label">Worst Case Error (VaR 95%)</div>
    <div class="metric-value">±{rec['var_95']:.0f} units</div></div>
</div></div>
<div class="section"><h2>Financing Recommendation</h2>
  <div class="recommendation-box"><h2>{method}</h2>
    <p>Recommended financing method based on cost ratio and demand risk profile</p></div>
  <div class="justification">{rec['rationale']}</div>
</div>
<div class="section"><h2>Financing Method Comparison</h2><table>
  <tr><th>Method</th><th>Best When</th><th>Retailer Risk</th><th>Selected</th></tr>
  <tr><td>Early Payment</td><td>Cost ratio &lt; 0.40</td><td>High</td><td>{sel['Early Payment']}</td></tr>
  <tr><td>In-House Factoring</td><td>Cost ratio 0.40 – 0.70</td><td>Medium</td><td>{sel['In-House Factoring']}</td></tr>
  <tr><td>Bank Financing</td><td>Cost ratio &gt; 0.70</td><td>Low</td><td>{sel['Bank Financing']}</td></tr>
</table></div>
<div class="footer">
  <p>Reference: Chen, X., Lu, Q., &amp; Cai, G. (2020). Buyer Financing in Pull
  Supply Chains. <em>Production and Operations Management.</em></p>
  <p>Generated by AI-Powered Supply Chain Finance Advisor (v2)</p>
</div></body></html>"""
